FROM ubuntu:jammy

ENV TZ Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./pyapp /home/ninja/pyapp
WORKDIR /home/ninja/pyapp/
RUN apt update && \
    apt install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools libmysqlclient-dev -y && \
    pip install wheel && \
    mkdir -p /home/ninja/pyapp && \
    pip install -r /home/ninja/pyapp/requirements.txt

EXPOSE 8000

COPY ./start_py.sh /root/start.sh
CMD ["/root/start.sh"]
